### ISSUE TITLE
plugins/DremelOutputDevice folder

### ISSUE THREAD

**Issue by WeavingColors** [timmehtimmeh/Cura-Dremel-3D20-Plugin#1]
Hello! 

"plugins/DremelOutputDevice" folder does not exist in the zip file download posted on this site. 
 
I am encountering an error when trying to save the Dremel file in Cura. 
The error states that the DremelOutputDevice does not exist on the computer I am working on.

Thank you so much for your assistance and guidance.

**Comment by timmehtimmeh** [comment]
Hi - sorry, there was an error in the documentation that's been fixed now.  you should copy plugins/DremelGCodeWriter to the plugins folder of your cura install

**Comment by WeavingColors** [comment]
That is exactly what I thought the issue was. 
Luckily, I assumed that was the issue and tried that out.
Unfortunately, I am still experiencing an error when saving the file. 

The Dremel 3D20 just doesn't want to budge. Im not sure what to do. 
I followed all of the directions you have posted and it seems to work correctly.
It just wont print. 

(I work for the Pima County Public Library in the 101 Space and we are trying to use Cura to print our files...Thank you sooo much from PCPL!)

**Comment by WeavingColors** [comment]
I will attempt to screen capture the error screen that pops up in Cura and post it to this thread.

**Comment by timmehtimmeh** [comment]
@WeavingColors  - thanks for helping debug this - I'll look into the issue tonight.

**Comment by WeavingColors** [comment]
Also, the Cura logo does not pop up as the preview on the Dremel. It is just blank. 

@timmehtimmeh You are most certainly welcome! Thank you so much for making this a reality. We appreciate your assistance and guidance.

**Comment by timmehtimmeh** [comment]
@WeavingColors  - when you post screenshots, could you also see if you could post the .g3drem file that was generated...thanks

**Comment by WeavingColors** [comment]
@timmehtimmeh Yeah! Will do. I will post ASAP.

**Comment by timmehtimmeh** [comment]
@WeavingColors - also if you could let me know which OS and version of cura you're using that would help greatly

**Comment by WeavingColors** [comment]
![comp info](https://user-images.githubusercontent.com/33734806/32918830-eb659b4c-cae0-11e7-9ae6-b56b88ed4875.PNG)
![cura info](https://user-images.githubusercontent.com/33734806/32918831-eb846234-cae0-11e7-8bae-089321f8223d.PNG)
![error message](https://user-images.githubusercontent.com/33734806/32918832-eba3027a-cae0-11e7-8f5f-ff44df725e79.PNG)

**Comment by WeavingColors** [comment]
[Dremel File.zip](https://github.com/timmehtimmeh/Cura-Dremel-3D20-Plugin/files/1480434/Dremel.File.zip)

**Comment by WeavingColors** [comment]
I believe that is everything you requested. Please let me know if I can provide additional information.

**Comment by timmehtimmeh** [comment]
@WeavingColors - awesome...thanks for the info.  As suspected the plugin wasn't finding the cura bitmap.  I've moved the bitmap data inside the plugin, so download the zip file again, and overwrite plugins/DremelGCodeWriter/DremelGCodeWriter.py with the new one.  Let me know if the new version works for you.

**Comment by WeavingColors** [comment]
Absolutely lovely! The printer is up and running now!

Thank you so much from me, PCPL, and the 101 Space staff.
You have been absolutely terrific!

Best wishes!

**Comment by timmehtimmeh** [comment]
Awesome to hear. Thanks for your help as well.  Next time I'm in Tucson maybe I'll swing by to check out your setup.
